#tokenize
input: /storage5/shared/corpus/0615llmjp_corpus_v2/batch_jsonl
#tokenize
input_tokenizer_file: /storage5/tokenizer/ja53K_en13K_add_dummy.model
output_prefix: /storage5/shared/corpus/2nd_tonyu/tokenized/llmjp/
workers: 64
megatron_deepspeed_dir: Megatron-DeepSpeed
