#tokenize
input: /storage5/shared/k_nishizawa/tmp_2nd_tounyu_2/merged_jsonl/merged_output.jsonl
#tokenize
input_tokenizer_file: /storage5/tokenizer/ja53K_en13K_add_dummy.model
output_prefix: /storage5/shared/k_nishizawa/tmp_2nd_tounyu_2/tokenized/
#output_prefix: /data/hatakeyama/python/llm_corpus/BTM_J_corpus
megatron_deepspeed_dir: Megatron-DeepSpeed
