#tokenize
input: /home/knishizawa/Matsuo_AI/LLM/data_set/hanrei_jsonl
#tokenize
input_tokenizer_file: /home/knishizawa/Matsuo_AI/LLM/ja53K_en13K_add_dummy/ja53K_en13K_add_dummy.model
output_prefix: /home/knishizawa/Matsuo_AI/LLM/tokenized_data/
workers: 26
megatron_deepspeed_dir: Megatron-DeepSpeed