#tokenize
input: /storage5/shared/corpus/pmc/PMC/merged_jsonl
#tokenize
input_tokenizer_file: /storage5/shared/corpus/phase1_tokenizer_data/tokernizer/tokenizer_scale200.model
output_prefix: /storage5/shared/corpus/re_tokenize_tokenizer_scale200/pmc/
workers: 4
megatron_deepspeed_dir: Megatron-DeepSpeed
