#tokenize
input: /storage5/shared/k_nishizawa/tmp_p1_token/jsonl
#tokenize
input_tokenizer_file: /storage5/tokenizer/ja53K_en13K_add_dummy.model
output_prefix: /storage5/shared/k_nishizawa/tmp_p1_token/tokenized/
workers: 64
megatron_deepspeed_dir: Megatron-DeepSpeed
